### ISSUE TITLE
App hides mobile OS title bar and navigation buttons

### ISSUE THREAD

**Issue by olivier-basille** [GameWithPixels/PixelsApp#46]
Currently the app runs full screen, check if it can ran more like a regular app

**Comment by Top64** [comment]
Its not a bad thing actually, it uses all the screen in a phone with curved corners

**Comment by olivier-basille** [comment]
Unity won't show Android status bar, even if full screen is off 
    There is a plugin to get around that, but it seems to be too much trouble for what it's worth 
    https://github.com/Over17/UnityShowAndroidStatusBar
