### ISSUE TITLE
Error in firmware info

### ISSUE THREAD

**Issue by nikolasbasler** [GameWithPixels/PixelsApp#79]
Hi,
when I open the "Dice Firmware Information", I see an error message and I'm not sure if there is a newer firmware available for my dice. The error message also appears when there is no die connected.

I hope you don't mind me being lazy and just attaching screenshots for details. Let me know if you need more information.

Best,
Nikolas

![signal-2024-07-08-182823_005](https://github.com/GameWithPixels/PixelsApp/assets/44873904/bfee407e-8233-4d20-9078-dc4e88f053e1)
![signal-2024-07-08-182823_002](https://github.com/GameWithPixels/PixelsApp/assets/44873904/7147386d-bacf-4773-8a0d-f1773f13acd0)
![signal-2024-07-08-182823_003](https://github.com/GameWithPixels/PixelsApp/assets/44873904/940374bd-02b4-4e10-a557-fc2ec7ef91ea)
![signal-2024-07-08-182823_004](https://github.com/GameWithPixels/PixelsApp/assets/44873904/92ab782e-06d9-4fae-9ef6-4a9435daa44c)

**Comment by obasille** [comment]
Hi @nikolasbasler,
Thank you for reporting this issue :)
I've just pushed a patch, the app should prompt you about installing it the next time your run it.
Your die is running with the latest firmware, so need to update it.
